version: '1'

services:
  # Database
  db:
    image: renzy0113/catapi-db:v3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catdb
      MYSQL_USER: catuser
      MYSQL_PASSWORD: catpassword
    networks:
      - iona
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - iona
  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: 
      - ./catAPI:/var/www/html/wp-content/plugins/catAPI # Plugin development
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: catdb
      WORDPRESS_DB_USER: catuser
      WORDPRESS_DB_PASSWORD: catpassword
      CATAPI_KEY: live_8X6H2QdzcRenW1baWJQgdDxx5SXn66ION9C1X6pnTnmGaPFaAnMCl9dKnYQbP07N
    networks:
      - iona
networks:
  iona:
volumes:
  db_data: